---
version: "3.4"
services:
  mongodb:
    image: mongo:4.4.24
    container_name: unifi-mongodb
    networks:
      - network-bridge-unifi
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ~/.unifi/mongo:/data/db
    ports:
      - 27017:27017

  unifi-network-application:
    depends_on:
      mongodb:
        condition: service_healthy
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi-network-application
    hostname: unifi
    networks:
      - network-bridge-unifi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Brisbane
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
      - MONGO_USER=unifi
      - MONGO_PASS=<mongdb_pass>
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
    volumes:
      - ~/.unifi/config:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped

networks:
  network-bridge-unifi:
    name: network-bridge-unifi
    driver: host # bridge host
